site_background_light:
  default: ""
  type: string

site_background_dark:
  default: ""
  type: string

category_card_1:
  default: 0
  type: integer

category_card_2:
  default: 0
  type: integer

category_card_3:
  default: 0
  type: integer
